/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardQuestionsRouteImport } from './routes/dashboard/questions'
import { Route as DashboardPracticeRouteImport } from './routes/dashboard/practice'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard/performance'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardQuestionsIndexRouteImport } from './routes/dashboard/questions/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardQuestionsPracticeRouteImport } from './routes/dashboard/questions/practice'
import { Route as DashboardQuestionsBankRouteImport } from './routes/dashboard/questions/bank'
import { Route as DashboardAdminQuestionsRouteImport } from './routes/dashboard/admin/questions'
import { Route as DashboardAdminCategoriesRouteImport } from './routes/dashboard/admin/categories'
import { Route as DashboardQuestionsAnswerQuestionIdRouteImport } from './routes/dashboard/questions/answer.$questionId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuestionsRoute = DashboardQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPracticeRoute = DashboardPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuestionsIndexRoute = DashboardQuestionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardQuestionsRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardQuestionsPracticeRoute =
  DashboardQuestionsPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => DashboardQuestionsRoute,
  } as any)
const DashboardQuestionsBankRoute = DashboardQuestionsBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => DashboardQuestionsRoute,
} as any)
const DashboardAdminQuestionsRoute = DashboardAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminCategoriesRoute =
  DashboardAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardQuestionsAnswerQuestionIdRoute =
  DashboardQuestionsAnswerQuestionIdRouteImport.update({
    id: '/answer/$questionId',
    path: '/answer/$questionId',
    getParentRoute: () => DashboardQuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/questions': typeof DashboardQuestionsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/questions/bank': typeof DashboardQuestionsBankRoute
  '/dashboard/questions/practice': typeof DashboardQuestionsPracticeRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/questions/': typeof DashboardQuestionsIndexRoute
  '/dashboard/questions/answer/$questionId': typeof DashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/questions/bank': typeof DashboardQuestionsBankRoute
  '/dashboard/questions/practice': typeof DashboardQuestionsPracticeRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/questions': typeof DashboardQuestionsIndexRoute
  '/dashboard/questions/answer/$questionId': typeof DashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/questions': typeof DashboardQuestionsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/questions/bank': typeof DashboardQuestionsBankRoute
  '/dashboard/questions/practice': typeof DashboardQuestionsPracticeRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/questions/': typeof DashboardQuestionsIndexRoute
  '/dashboard/questions/answer/$questionId': typeof DashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/categories'
    | '/dashboard/performance'
    | '/dashboard/practice'
    | '/dashboard/questions'
    | '/dashboard/'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/questions'
    | '/dashboard/questions/bank'
    | '/dashboard/questions/practice'
    | '/dashboard/admin/'
    | '/dashboard/questions/'
    | '/dashboard/questions/answer/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/categories'
    | '/dashboard/performance'
    | '/dashboard/practice'
    | '/dashboard'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/questions'
    | '/dashboard/questions/bank'
    | '/dashboard/questions/practice'
    | '/dashboard/admin'
    | '/dashboard/questions'
    | '/dashboard/questions/answer/$questionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/categories'
    | '/dashboard/performance'
    | '/dashboard/practice'
    | '/dashboard/questions'
    | '/dashboard/'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/questions'
    | '/dashboard/questions/bank'
    | '/dashboard/questions/practice'
    | '/dashboard/admin/'
    | '/dashboard/questions/'
    | '/dashboard/questions/answer/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/questions': {
      id: '/dashboard/questions'
      path: '/questions'
      fullPath: '/dashboard/questions'
      preLoaderRoute: typeof DashboardQuestionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/practice': {
      id: '/dashboard/practice'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof DashboardPracticeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/questions/': {
      id: '/dashboard/questions/'
      path: '/'
      fullPath: '/dashboard/questions/'
      preLoaderRoute: typeof DashboardQuestionsIndexRouteImport
      parentRoute: typeof DashboardQuestionsRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/questions/practice': {
      id: '/dashboard/questions/practice'
      path: '/practice'
      fullPath: '/dashboard/questions/practice'
      preLoaderRoute: typeof DashboardQuestionsPracticeRouteImport
      parentRoute: typeof DashboardQuestionsRoute
    }
    '/dashboard/questions/bank': {
      id: '/dashboard/questions/bank'
      path: '/bank'
      fullPath: '/dashboard/questions/bank'
      preLoaderRoute: typeof DashboardQuestionsBankRouteImport
      parentRoute: typeof DashboardQuestionsRoute
    }
    '/dashboard/admin/questions': {
      id: '/dashboard/admin/questions'
      path: '/questions'
      fullPath: '/dashboard/admin/questions'
      preLoaderRoute: typeof DashboardAdminQuestionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/categories': {
      id: '/dashboard/admin/categories'
      path: '/categories'
      fullPath: '/dashboard/admin/categories'
      preLoaderRoute: typeof DashboardAdminCategoriesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/questions/answer/$questionId': {
      id: '/dashboard/questions/answer/$questionId'
      path: '/answer/$questionId'
      fullPath: '/dashboard/questions/answer/$questionId'
      preLoaderRoute: typeof DashboardQuestionsAnswerQuestionIdRouteImport
      parentRoute: typeof DashboardQuestionsRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminCategoriesRoute: typeof DashboardAdminCategoriesRoute
  DashboardAdminQuestionsRoute: typeof DashboardAdminQuestionsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminCategoriesRoute: DashboardAdminCategoriesRoute,
  DashboardAdminQuestionsRoute: DashboardAdminQuestionsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardQuestionsRouteChildren {
  DashboardQuestionsBankRoute: typeof DashboardQuestionsBankRoute
  DashboardQuestionsPracticeRoute: typeof DashboardQuestionsPracticeRoute
  DashboardQuestionsIndexRoute: typeof DashboardQuestionsIndexRoute
  DashboardQuestionsAnswerQuestionIdRoute: typeof DashboardQuestionsAnswerQuestionIdRoute
}

const DashboardQuestionsRouteChildren: DashboardQuestionsRouteChildren = {
  DashboardQuestionsBankRoute: DashboardQuestionsBankRoute,
  DashboardQuestionsPracticeRoute: DashboardQuestionsPracticeRoute,
  DashboardQuestionsIndexRoute: DashboardQuestionsIndexRoute,
  DashboardQuestionsAnswerQuestionIdRoute:
    DashboardQuestionsAnswerQuestionIdRoute,
}

const DashboardQuestionsRouteWithChildren =
  DashboardQuestionsRoute._addFileChildren(DashboardQuestionsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardPracticeRoute: typeof DashboardPracticeRoute
  DashboardQuestionsRoute: typeof DashboardQuestionsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardPracticeRoute: DashboardPracticeRoute,
  DashboardQuestionsRoute: DashboardQuestionsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
