/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardQuestionsIndexRouteImport } from './routes/dashboard/questions/index'
import { Route as DashboardPracticeIndexRouteImport } from './routes/dashboard/practice/index'
import { Route as DashboardPerformanceIndexRouteImport } from './routes/dashboard/performance/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAdminQuestionsRouteImport } from './routes/dashboard/admin/questions'
import { Route as DashboardAdminCategoriesRouteImport } from './routes/dashboard/admin/categories'
import { Route as DashboardQuestionsAnswerQuestionIdRouteImport } from './routes/dashboard/questions/answer.$questionId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuestionsIndexRoute = DashboardQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPracticeIndexRoute = DashboardPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceIndexRoute =
  DashboardPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminQuestionsRoute = DashboardAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminCategoriesRoute =
  DashboardAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardQuestionsAnswerQuestionIdRoute =
  DashboardQuestionsAnswerQuestionIdRouteImport.update({
    id: '/questions/answer/$questionId',
    path: '/questions/answer/$questionId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/performance': typeof DashboardPerformanceIndexRoute
  '/dashboard/practice': typeof DashboardPracticeIndexRoute
  '/dashboard/questions': typeof DashboardQuestionsIndexRoute
  '/dashboard/questions/answer/$questionId': typeof DashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/performance': typeof DashboardPerformanceIndexRoute
  '/dashboard/practice': typeof DashboardPracticeIndexRoute
  '/dashboard/questions': typeof DashboardQuestionsIndexRoute
  '/dashboard/questions/answer/$questionId': typeof DashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/categories': typeof DashboardAdminCategoriesRoute
  '/dashboard/admin/questions': typeof DashboardAdminQuestionsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/performance/': typeof DashboardPerformanceIndexRoute
  '/dashboard/practice/': typeof DashboardPracticeIndexRoute
  '/dashboard/questions/': typeof DashboardQuestionsIndexRoute
  '/dashboard/questions/answer/$questionId': typeof DashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/questions'
    | '/dashboard/admin/'
    | '/dashboard/categories'
    | '/dashboard/performance'
    | '/dashboard/practice'
    | '/dashboard/questions'
    | '/dashboard/questions/answer/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/questions'
    | '/dashboard/admin'
    | '/dashboard/categories'
    | '/dashboard/performance'
    | '/dashboard/practice'
    | '/dashboard/questions'
    | '/dashboard/questions/answer/$questionId'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/questions'
    | '/dashboard/admin/'
    | '/dashboard/categories/'
    | '/dashboard/performance/'
    | '/dashboard/practice/'
    | '/dashboard/questions/'
    | '/dashboard/questions/answer/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/questions/': {
      id: '/dashboard/questions/'
      path: '/questions'
      fullPath: '/dashboard/questions'
      preLoaderRoute: typeof DashboardQuestionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/practice/': {
      id: '/dashboard/practice/'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof DashboardPracticeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance/': {
      id: '/dashboard/performance/'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/questions': {
      id: '/dashboard/admin/questions'
      path: '/questions'
      fullPath: '/dashboard/admin/questions'
      preLoaderRoute: typeof DashboardAdminQuestionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/categories': {
      id: '/dashboard/admin/categories'
      path: '/categories'
      fullPath: '/dashboard/admin/categories'
      preLoaderRoute: typeof DashboardAdminCategoriesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/questions/answer/$questionId': {
      id: '/dashboard/questions/answer/$questionId'
      path: '/questions/answer/$questionId'
      fullPath: '/dashboard/questions/answer/$questionId'
      preLoaderRoute: typeof DashboardQuestionsAnswerQuestionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminCategoriesRoute: typeof DashboardAdminCategoriesRoute
  DashboardAdminQuestionsRoute: typeof DashboardAdminQuestionsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminCategoriesRoute: DashboardAdminCategoriesRoute,
  DashboardAdminQuestionsRoute: DashboardAdminQuestionsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardPerformanceIndexRoute: typeof DashboardPerformanceIndexRoute
  DashboardPracticeIndexRoute: typeof DashboardPracticeIndexRoute
  DashboardQuestionsIndexRoute: typeof DashboardQuestionsIndexRoute
  DashboardQuestionsAnswerQuestionIdRoute: typeof DashboardQuestionsAnswerQuestionIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardPerformanceIndexRoute: DashboardPerformanceIndexRoute,
  DashboardPracticeIndexRoute: DashboardPracticeIndexRoute,
  DashboardQuestionsIndexRoute: DashboardQuestionsIndexRoute,
  DashboardQuestionsAnswerQuestionIdRoute:
    DashboardQuestionsAnswerQuestionIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
