/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedDashboardQuestionsIndexRouteImport } from './routes/_authenticated/dashboard/questions/index'
import { Route as AuthenticatedDashboardPracticeIndexRouteImport } from './routes/_authenticated/dashboard/practice/index'
import { Route as AuthenticatedDashboardPerformanceIndexRouteImport } from './routes/_authenticated/dashboard/performance/index'
import { Route as AuthenticatedDashboardCategoriesIndexRouteImport } from './routes/_authenticated/dashboard/categories/index'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard/admin/index'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard/admin/users'
import { Route as AuthenticatedDashboardAdminQuestionsRouteImport } from './routes/_authenticated/dashboard/admin/questions'
import { Route as AuthenticatedDashboardAdminCategoriesRouteImport } from './routes/_authenticated/dashboard/admin/categories'
import { Route as AuthenticatedDashboardQuestionsAnswerQuestionIdRouteImport } from './routes/_authenticated/dashboard/questions/answer.$questionId'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQuestionsIndexRoute =
  AuthenticatedDashboardQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPracticeIndexRoute =
  AuthenticatedDashboardPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPerformanceIndexRoute =
  AuthenticatedDashboardPerformanceIndexRouteImport.update({
    id: '/performance/',
    path: '/performance/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesIndexRoute =
  AuthenticatedDashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminQuestionsRoute =
  AuthenticatedDashboardAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminCategoriesRoute =
  AuthenticatedDashboardAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardQuestionsAnswerQuestionIdRoute =
  AuthenticatedDashboardQuestionsAnswerQuestionIdRouteImport.update({
    id: '/questions/answer/$questionId',
    path: '/questions/answer/$questionId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/categories': typeof AuthenticatedDashboardAdminCategoriesRoute
  '/dashboard/admin/questions': typeof AuthenticatedDashboardAdminQuestionsRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceIndexRoute
  '/dashboard/practice': typeof AuthenticatedDashboardPracticeIndexRoute
  '/dashboard/questions': typeof AuthenticatedDashboardQuestionsIndexRoute
  '/dashboard/questions/answer/$questionId': typeof AuthenticatedDashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/categories': typeof AuthenticatedDashboardAdminCategoriesRoute
  '/dashboard/admin/questions': typeof AuthenticatedDashboardAdminQuestionsRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceIndexRoute
  '/dashboard/practice': typeof AuthenticatedDashboardPracticeIndexRoute
  '/dashboard/questions': typeof AuthenticatedDashboardQuestionsIndexRoute
  '/dashboard/questions/answer/$questionId': typeof AuthenticatedDashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/categories': typeof AuthenticatedDashboardAdminCategoriesRoute
  '/_authenticated/dashboard/admin/questions': typeof AuthenticatedDashboardAdminQuestionsRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/_authenticated/dashboard/categories/': typeof AuthenticatedDashboardCategoriesIndexRoute
  '/_authenticated/dashboard/performance/': typeof AuthenticatedDashboardPerformanceIndexRoute
  '/_authenticated/dashboard/practice/': typeof AuthenticatedDashboardPracticeIndexRoute
  '/_authenticated/dashboard/questions/': typeof AuthenticatedDashboardQuestionsIndexRoute
  '/_authenticated/dashboard/questions/answer/$questionId': typeof AuthenticatedDashboardQuestionsAnswerQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/questions'
    | '/dashboard/admin/users'
    | '/dashboard/admin/'
    | '/dashboard/categories'
    | '/dashboard/performance'
    | '/dashboard/practice'
    | '/dashboard/questions'
    | '/dashboard/questions/answer/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/dashboard/admin/categories'
    | '/dashboard/admin/questions'
    | '/dashboard/admin/users'
    | '/dashboard/admin'
    | '/dashboard/categories'
    | '/dashboard/performance'
    | '/dashboard/practice'
    | '/dashboard/questions'
    | '/dashboard/questions/answer/$questionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/categories'
    | '/_authenticated/dashboard/admin/questions'
    | '/_authenticated/dashboard/admin/users'
    | '/_authenticated/dashboard/admin/'
    | '/_authenticated/dashboard/categories/'
    | '/_authenticated/dashboard/performance/'
    | '/_authenticated/dashboard/practice/'
    | '/_authenticated/dashboard/questions/'
    | '/_authenticated/dashboard/questions/answer/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/questions/': {
      id: '/_authenticated/dashboard/questions/'
      path: '/questions'
      fullPath: '/dashboard/questions'
      preLoaderRoute: typeof AuthenticatedDashboardQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/practice/': {
      id: '/_authenticated/dashboard/practice/'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof AuthenticatedDashboardPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/performance/': {
      id: '/_authenticated/dashboard/performance/'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof AuthenticatedDashboardPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories/': {
      id: '/_authenticated/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/questions': {
      id: '/_authenticated/dashboard/admin/questions'
      path: '/questions'
      fullPath: '/dashboard/admin/questions'
      preLoaderRoute: typeof AuthenticatedDashboardAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/categories': {
      id: '/_authenticated/dashboard/admin/categories'
      path: '/categories'
      fullPath: '/dashboard/admin/categories'
      preLoaderRoute: typeof AuthenticatedDashboardAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/questions/answer/$questionId': {
      id: '/_authenticated/dashboard/questions/answer/$questionId'
      path: '/questions/answer/$questionId'
      fullPath: '/dashboard/questions/answer/$questionId'
      preLoaderRoute: typeof AuthenticatedDashboardQuestionsAnswerQuestionIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardAdminRouteChildren {
  AuthenticatedDashboardAdminCategoriesRoute: typeof AuthenticatedDashboardAdminCategoriesRoute
  AuthenticatedDashboardAdminQuestionsRoute: typeof AuthenticatedDashboardAdminQuestionsRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
}

const AuthenticatedDashboardAdminRouteChildren: AuthenticatedDashboardAdminRouteChildren =
  {
    AuthenticatedDashboardAdminCategoriesRoute:
      AuthenticatedDashboardAdminCategoriesRoute,
    AuthenticatedDashboardAdminQuestionsRoute:
      AuthenticatedDashboardAdminQuestionsRoute,
    AuthenticatedDashboardAdminUsersRoute:
      AuthenticatedDashboardAdminUsersRoute,
    AuthenticatedDashboardAdminIndexRoute:
      AuthenticatedDashboardAdminIndexRoute,
  }

const AuthenticatedDashboardAdminRouteWithChildren =
  AuthenticatedDashboardAdminRoute._addFileChildren(
    AuthenticatedDashboardAdminRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCategoriesIndexRoute: typeof AuthenticatedDashboardCategoriesIndexRoute
  AuthenticatedDashboardPerformanceIndexRoute: typeof AuthenticatedDashboardPerformanceIndexRoute
  AuthenticatedDashboardPracticeIndexRoute: typeof AuthenticatedDashboardPracticeIndexRoute
  AuthenticatedDashboardQuestionsIndexRoute: typeof AuthenticatedDashboardQuestionsIndexRoute
  AuthenticatedDashboardQuestionsAnswerQuestionIdRoute: typeof AuthenticatedDashboardQuestionsAnswerQuestionIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute:
      AuthenticatedDashboardAdminRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCategoriesIndexRoute:
      AuthenticatedDashboardCategoriesIndexRoute,
    AuthenticatedDashboardPerformanceIndexRoute:
      AuthenticatedDashboardPerformanceIndexRoute,
    AuthenticatedDashboardPracticeIndexRoute:
      AuthenticatedDashboardPracticeIndexRoute,
    AuthenticatedDashboardQuestionsIndexRoute:
      AuthenticatedDashboardQuestionsIndexRoute,
    AuthenticatedDashboardQuestionsAnswerQuestionIdRoute:
      AuthenticatedDashboardQuestionsAnswerQuestionIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
